<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:RuntimeTypeConversionFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.RuntimeTypeConversionFunctions" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:tns="http://iec.ch/TC57/2011/VehiclesCoordinatesMessage" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl tns UUIDUserFunction IsUserInGroupFunction oraext IsUserInRoleFunction xp20 DVMFunctions oraxsl RuntimeTypeConversionFunctions XrefFunctions BasicCredentialsUserFunction">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="Schemas/input-VehiclesCoordinates-.xsd"/>
            <oracle-xsl-mapper:rootElement name="VehiclesCoordinates" namespace=""/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="Schemas/output-ChangedVehiclesCoordinates-http___iec_ch_TC57_2011_VehiclesCoordinatesMessage.xsd"/>
            <oracle-xsl-mapper:rootElement name="ChangedVehiclesCoordinates" namespace="http://iec.ch/TC57/2011/VehiclesCoordinatesMessage"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.2.0(XSLT Build 161003.0739.0018) AT [FRI APR 30 21:04:49 CST 2021].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
		      <tns:ChangedVehiclesCoordinates>
		         <tns:Header>
		            <Verb xmlns="http://iec.ch/TC57/2011/schema/message">changed</Verb>
		            <Noun xmlns="http://iec.ch/TC57/2011/schema/message">VehiclesCoordinates</Noun>
		            <Revision xmlns="http://iec.ch/TC57/2011/schema/message">2.0</Revision>
		            <Timestamp xmlns="http://iec.ch/TC57/2011/schema/message">2021-05-05T02:18:37+02:00</Timestamp>
		            <Source xmlns="http://iec.ch/TC57/2011/schema/message">AVL</Source>
		            <MessageID xmlns="http://iec.ch/TC57/2011/schema/message">12345</MessageID>
		            <CorrelationID xmlns="http://iec.ch/TC57/2011/schema/message">12345</CorrelationID>
		         </tns:Header>
		         <tns:Payload>
		            <tns:VehiclesCoordinates>
		               <Vehicle xmlns="http://iec.ch/TC57/2007/VehiclesCoordinates#">
		                  <mRID xmlns="http://iec.ch/TC57/2007/VehiclesCoordinates#">
		                     <xsl:value-of select="/RestRequestVehiclesCoordinates/@vID"/>
		                  </mRID>
		                  <odometerReadDateTime xmlns="http://iec.ch/TC57/2007/VehiclesCoordinates#"></odometerReadDateTime>
		                  <PositionPoint xmlns="http://iec.ch/TC57/2007/VehiclesCoordinates#">
		                     <xPosition xmlns="http://iec.ch/TC57/2007/VehiclesCoordinates#">
		                        <xsl:value-of select="/RestRequestVehiclesCoordinates/@xPosition"/>
		                     </xPosition>
		                     <yPosition xmlns="http://iec.ch/TC57/2007/VehiclesCoordinates#">
		                        <xsl:value-of select="/RestRequestVehiclesCoordinates/@yPosition"/>
		                     </yPosition>
		                  </PositionPoint>
		               </Vehicle>
		            </tns:VehiclesCoordinates>
		         </tns:Payload>
		      </tns:ChangedVehiclesCoordinates>
   </xsl:template>
</xsl:stylesheet>
